Raise minimum rustc version in CI to 1.56
Required by use of 2021 edition in hashbrown:

    error: failed to download `hashbrown v0.12.0`

    Caused by:
      unable to get packages from source

    Caused by:
      failed to parse manifest at `github.com-1ecc6299db9ec823/hashbrown-0.12.0/Cargo.toml`

    Caused by:
      feature `edition2021` is required

      The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0 (32da73ab1 2021-08-23)).
      Consider trying a newer version of Cargo (this may require the nightly release).
      See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.