Raise minimum rustc version in CI to 1.52
Required by the time crate:

    error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
       --> github.com-1ecc6299db9ec823/time-0.3.6/src/lib.rs:88:1
        |
    88  | / #![deny(
    89  | |     anonymous_parameters,
    90  | |     clippy::all,
    91  | |     const_err,
    ...   |
    102 | |     unused_extern_crates
    103 | | )]
        | |__^