Raise minimum tested compiler to 1.70
Required by simd-json's use of standard library OnceCell.

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:380:24
        |
    380 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:385:24
        |
    385 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:555:24
        |
    555 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:560:24
        |
    560 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:380:24
        |
    380 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:381:43
        |
    381 |             let avx_support: &bool = cell.get_or_init(|| std::is_x86_feature_detected!("avx2"));
        |                                           ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:385:24
        |
    385 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:386:43
        |
    386 |             let sse_support: &bool = cell.get_or_init(|| std::is_x86_feature_detected!("sse4.2"));
        |                                           ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:555:24
        |
    555 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:556:43
        |
    556 |             let avx_support: &bool = cell.get_or_init(|| std::is_x86_feature_detected!("avx2"));
        |                                           ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:560:24
        |
    560 |             let cell = std::cell::OnceCell::new();
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'once_cell'
       --> github.com-1ecc6299db9ec823/simd-json-0.11.0/src/lib.rs:561:43
        |
    561 |             let sse_support: &bool = cell.get_or_init(|| std::is_x86_feature_detected!("sse4.2"));
        |                                           ^^^^^^^^^^^