Raise minimum tested toolchain to rust 1.61
Required by the transitive dependency on hashbrown.

    error: package `hashbrown v0.13.1` cannot be built because it
    requires rustc 1.61.0 or newer, while the currently active rustc
    version is 1.60.0