Raise minimum rustc version in CI to 1.59
Required by simd-json's dependency on value-trait:

    error: package `value-trait v0.2.12` cannot be built because it
    requires rustc 1.59 or newer, while the currently active rustc
    version is 1.56.0